{% set name = "fastremap" %}
{% set version = "1.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastremap-{{ version }}.tar.gz
  sha256: 7cfb7b952c5cae954863d63b671675088e07beef27eba7411b53c2c7c5b30958

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - numpy
    - pbr
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - fastremap
  commands:
    - pip list
    - pip check
    - python -c "import fastremap;import numpy as np;mappings={1:100,2:200,-3:7};arr=np.array([5,1,2,-5,-3,10,6]);print(fastremap.remap(arr,mappings,preserve_missing_labels=True))"
  requires:
    - numpy
    - pip

about:
  home: https://github.com/seung-lab/fastremap/
  summary: Remap, mask, renumber, unique, and in-place transposition of 3D labeled images. Point cloud too.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - william-silversmith
    - stuarteberg
